import unittest
from route_between_nodes import *


class GraphTest(unittest.TestCase):
  def setUp(self) -> None:
    self.graph = Graph(True)
  
  def test_1(self) -> None:
    self.graph.add_edge(1, 2)
    self.graph.add_edge(1, 3)
    self.graph.add_edge(2, 5)
    self.graph.add_edge(3, 4)
    self.graph.add_edge(3, 7)
    self.graph.add_edge(4, 1)
    self.graph.add_edge(4, 5)
    self.graph.add_edge(5, 1)
    self.graph.add_edge(6, 3)
    self.graph.add_edge(6, 4)
    self.graph.add_edge(6, 8)
    self.graph.add_edge(6, 10)
    self.graph.add_edge(7, 4)
    self.graph.add_edge(7, 9)
    self.graph.add_edge(8, 3)
    self.graph.add_edge(8, 7)
    self.graph.add_edge(9, 5)
    self.graph.add_edge(9, 6)
    self.graph.add_edge(9, 8)
    self.assertTrue(self.graph.path_exists(1, 10))
    
  def test_2(self) -> None:
    self.graph.add_edge(1, 2)
    self.graph.add_edge(1, 3)
    self.graph.add_edge(2, 5)
    self.graph.add_edge(3, 4)
    self.graph.add_edge(3, 7)
    self.graph.add_edge(4, 1)
    self.graph.add_edge(4, 5)
    self.graph.add_edge(5, 1)
    self.graph.add_edge(6, 3)
    self.graph.add_edge(6, 4)
    self.graph.add_edge(6, 8)
    self.graph.add_edge(6, 10)
    self.graph.add_edge(7, 4)
    self.graph.add_edge(7, 9)
    self.graph.add_edge(8, 3)
    self.graph.add_edge(8, 7)
    self.graph.add_edge(9, 5)
    self.graph.add_edge(9, 6)
    self.graph.add_edge(9, 8)
    self.graph.add_edge(11, 12)
    self.assertFalse(self.graph.path_exists(1, 12))
  
  def test_3(self) -> None:
    self.graph.add_edge(1, 2)
    self.graph.add_edge(1, 3)
    self.graph.add_edge(2, 5)
    self.graph.add_edge(3, 4)
    self.graph.add_edge(3, 7)
    self.graph.add_edge(4, 1)
    self.graph.add_edge(4, 5)
    self.graph.add_edge(5, 1)
    self.graph.add_edge(6, 3)
    self.graph.add_edge(6, 4)
    self.graph.add_edge(6, 8)
    self.graph.add_edge(6, 10)
    self.graph.add_edge(7, 4)
    self.graph.add_edge(7, 9)
    self.graph.add_edge(8, 3)
    self.graph.add_edge(8, 7)
    self.graph.add_edge(9, 5)
    self.graph.add_edge(9, 6)
    self.graph.add_edge(9, 8)
    self.assertFalse(self.graph.path_exists(1, 0))